### ISSUE TITLE
CompositeStateTrigger cannot have AdaptiveTrigger in collection

### ISSUE THREAD

**Issue by sibbl** [dotMorten/WindowsStateTriggers#47] opened 2015-09-20 09:56 UTC
Unfortunately the following code does not work, but I'd love to have setters for e.g. "desktop device family and window width greater than 500px":

```
<VisualState.StateTriggers>
    <windowsStateTriggers:CompositeStateTrigger Operator="And">
        <windowsStateTriggers:DeviceFamilyStateTrigger DeviceFamily="Desktop" />
        <AdaptiveTrigger MinWindowWidth="500" />
    </windowsStateTriggers:CompositeStateTrigger>
</VisualState.StateTriggers>
```

Is there anything that can be done?

**Comment by rexobias** [comment] 2015-09-28 11:05
I have the same question.

**Comment by tibitoth** [comment] 2015-10-20 20:16
We can't use the `AdaptiveTrigger` in `CompositeStateTrigger`, because it isn't implement the `ITriggerValue` interface. I think we need to reimplement this trigger.

**Comment by tibitoth** [comment] 2015-10-20 22:08
I created a pull request #48 with `ITriggerValue` implementation.

**Comment by dotMorten** [comment] 2015-10-20 22:14
@totht91 Thanks nice job, but is there a reason we wouldn't just still call it "AdaptiveTrigger" ?

**Comment by tibitoth** [comment] 2015-10-21 09:46
We can call it :+1:

**Comment by rexobias** [comment] 2015-10-22 10:21
Thank you ;)

**Comment by tibitoth** [comment] 2015-10-22 14:12
NP. But it's not merged yet.

**Comment by sibbl** [comment] 2015-11-07 10:46
@dotMorten may I ask why this is still not merged? It would be good for this project to have the `AdaptiveTrigger` merged, wouldn't it?

**Comment by tibitoth** [comment] 2016-01-15 22:00
It's feel like an abandoned repo.

**Comment by dotMorten** [comment] 2016-01-15 22:52
@sibbl or like WPF it's 'mature' :) The question I asked last wasn't answered.

**Comment by tibitoth** [comment] 2016-01-20 10:25
So WindowsStateTriggers is mature?

**Comment by sibbl** [comment] 2016-01-20 11:06
If I'm correct, you, @dotMorten, want @totht91 to rename the `CompositableAdaptiveTrigger` to `AdaptiveTrigger`, right? Or are you waiting for more changes to merge the new PR and release the new version on Nuget?

**Comment by tibitoth** [comment] 2016-01-20 11:09
I renamed it. https://github.com/totht91/WindowsStateTriggers/commit/139ea9fde0e037c5c5206d775aca42eb7764a6db

**Comment by sibbl** [comment] 2016-01-20 11:34
Oh, indeed - sorry, @totht91. Okay, what answer for which question are you then waiting for, @dotMorten? ;)

**Comment by ndeeH** [comment] 2016-01-25 14:00
Please update the nuget version. Thank you.

**Comment by dotMorten** [comment] 2016-02-02 07:30
merged and nuget updated

**Closed as completed by dotMorten** 2016-02-02 07:30 UTC

**Comment by genfa** [comment] 2016-02-07 11:42
Hello, I'm currently trying to use the trigger in a UWP with several resolutions
`<WindowsStateTriggers:CompositeStateTrigger Operator="And" >
  <WindowsStateTriggers:AdaptiveTrigger MinWindowWidth="100"/>
  <WindowsStateTriggers:DeviceFamilyStateTrigger DeviceFamily="Desktop"/>
</WindowsStateTriggers:CompositeStateTrigger>
`
with the latest nugget package (02/02) but only the first visualstate is executed. Do you have a example to use the composite trigger?

**Comment by tibitoth** [comment] 2016-02-07 19:21
What do you mean "only the first visualstate is executed"? Your sample (min window width and device family) is worked for me flawlessly.

**Comment by genfa** [comment] 2016-02-07 21:30
If a second visual state is defined with a different resolution
`<WindowsStateTriggers:CompositeStateTrigger Operator="And" > <WindowsStateTriggers:AdaptiveTrigger MinWindowWidth="500"/> <WindowsStateTriggers:DeviceFamilyStateTrigger DeviceFamily="Desktop"/> </WindowsStateTriggers:CompositeStateTrigger>`
and I resize my app while running, to more then 500, the visual state is not applied. If I use only the builtin `<AdaptativeTrigger>`, everything run fine.
For my app, I use a VisualState for Phone (with the DeviceFamilyStateTrigger), and the other ones for the desktop without the DeviceFamilyStateTrigger and with the builtin AdaptativeTrigger.

**Comment by dotMorten** [comment] 2016-02-07 23:22
Could you please open an issue and post a full sample that demonstrates the problem?
I'm terrible at guessing reproducers ;-)

**Comment by genfa** [comment] 2016-02-08 08:42
I'll do it this evening.
A reproductible bug is half resolved :)
